/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.gltf --types --shadows --output src/Drum.tsx 
Author: Andrei V (https://sketchfab.com/vav206)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drum-3bdb9a685e834932a7f3ce226d7bd247
Title: Drum
*/

import * as THREE from "three"
import { Mask, useGLTF, useMask, useTexture } from "@react-three/drei"
import type { GLTF } from "three-stdlib"
import type { ThreeElements, ThreeEvent } from "@react-three/fiber"
import { useMemo, useRef, useState } from "react"
type DrumProps = ThreeElements["group"] & {
  onDraggingChange: (d: boolean) => void
}

type GLTFResult = GLTF & {
  nodes: {
    drum_drum_0: THREE.Mesh
    Plane001_logo_0: THREE.Mesh
    stick1_drum_0: THREE.Mesh
    stick002_drum_0: THREE.Mesh
  }
  materials: {
    drum: THREE.MeshStandardMaterial
    logo: THREE.MeshStandardMaterial
  }
}

// visible drum skin inside the hoop, in face-group units (centred on the face origin)
const HEAD_RADIUS = 800

function clampToHead(x: number, y: number): [number, number] {
  const r = Math.hypot(x, y)
  if (r <= HEAD_RADIUS) return [x, y]
  return [(x / r) * HEAD_RADIUS, (y / r) * HEAD_RADIUS]
}

// sticker size limits, as multiples of the original logo size
const MIN_SCALE = 0.1
const MAX_SCALE = 5
// grabbing right at the centre would make tiny movements scale hugely
const MIN_SCALE_GRAB_DIST = 50

// pixels at or below this alpha (0-255) don't count as part of the sticker
const ALPHA_THRESHOLD = 10

function readPixels(image: HTMLImageElement) {
  const canvas = document.createElement("canvas")
  canvas.width = image.width
  canvas.height = image.height
  const ctx = canvas.getContext("2d", { willReadFrequently: true })!
  ctx.drawImage(image, 0, 0)
  return ctx.getImageData(0, 0, canvas.width, canvas.height)
}

function isOpaqueAt(pixels: ImageData, uv: THREE.Vector2) {
  const x = Math.min(pixels.width - 1, Math.floor(uv.x * pixels.width))
  // flipY = true puts uv.y = 0 at the bottom row of the image
  const y = Math.min(pixels.height - 1, Math.floor((1 - uv.y) * pixels.height))
  return pixels.data[(y * pixels.width + x) * 4 + 3] > ALPHA_THRESHOLD
}

function hitOnFace(e: ThreeEvent<PointerEvent>) {
  const face = e.eventObject.parent!
  const normal = new THREE.Vector3(0, 0, 1).transformDirection(face.matrixWorld)
  const origin = new THREE.Vector3().setFromMatrixPosition(face.matrixWorld)
  const plane = new THREE.Plane().setFromNormalAndCoplanarPoint(normal, origin)
  const hit = e.ray.intersectPlane(plane, new THREE.Vector3())
  return hit ? face.worldToLocal(hit) : null
}

export function Drum({ onDraggingChange, ...props }: DrumProps) {
  const [pos, setPos] = useState<[number, number]>([0, 0])
  const [stickerScale, setStickerScale] = useState(1)
  const grabOffset = useRef<[number, number]>([0, 0])
  const scaleGrab = useRef({ dist: 1, scale: 1 })
  const { nodes, materials } = useGLTF("/scene.gltf") as unknown as GLTFResult
  const sticker = useTexture("/logos/sticker.png", (tex) => {
    tex.flipY = true
    tex.colorSpace = THREE.SRGBColorSpace
  })
  const [dragging, setDragging] = useState<"move" | "scale" | null>(null)
  const headMask = useMask(1)
  const stickerPixels = useMemo(
    () => readPixels(sticker.image as HTMLImageElement),
    [sticker],
  )

  function setDrag(mode: "move" | "scale" | null) {
    setDragging(mode)
    onDraggingChange(mode !== null)
  }
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.drum_drum_0.geometry}
            material={materials.drum}
            position={[0, 22.964, 344.032]}
          />
        </group>
        <group
          position={[-642.341, 739.525, -84.407]}
          rotation={[-Math.PI / 2, 0, 2.793]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stick1_drum_0.geometry}
            material={materials.drum}
            position={[1143.077, 261.301, -392.314]}
          />
        </group>
        <group
          position={[-608.566, 749.455, -67.994]}
          rotation={[-1.547, 0.058, -2.108]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stick002_drum_0.geometry}
            material={materials.drum}
            position={[1143.077, 261.301, -392.314]}
          />
        </group>
        <group
          position={[0, 376.885, 415.912]}
          rotation={[-0.075, 0, 0]}
          scale={0.381}
        >
          {/* nudged forward so it doesn't z-fight with the drum skin */}
          <Mask id={1} position={[0, 0, 2]}>
            <circleGeometry args={[HEAD_RADIUS, 96]} />
          </Mask>
          <mesh
            receiveShadow
            geometry={nodes.Plane001_logo_0.geometry}
            position={[pos[0], pos[1], 0]}
            scale={stickerScale}
            onPointerDown={(e) => {
              // left button moves, right button scales
              const mode =
                e.button === 0 ? "move" : e.button === 2 ? "scale" : null
              if (!mode) return
              // only grab the sticker on its visible pixels, and not where the mask has clipped it
              if (!e.uv || !isOpaqueAt(stickerPixels, e.uv)) return
              const hit = hitOnFace(e)
              if (!hit || Math.hypot(hit.x, hit.y) > HEAD_RADIUS) return
              e.stopPropagation()
              if (mode === "move") {
                grabOffset.current = [hit.x - pos[0], hit.y - pos[1]]
              } else {
                scaleGrab.current = {
                  dist: Math.max(
                    MIN_SCALE_GRAB_DIST,
                    Math.hypot(hit.x - pos[0], hit.y - pos[1]),
                  ),
                  scale: stickerScale,
                }
              }
              ;(e.target as Element).setPointerCapture(e.pointerId)
              setDrag(mode)
            }}
            onPointerMove={(e) => {
              if (!dragging) return
              const hit = hitOnFace(e)
              if (!hit) return
              if (dragging === "move") {
                setPos(
                  clampToHead(
                    hit.x - grabOffset.current[0],
                    hit.y - grabOffset.current[1],
                  ),
                )
              } else {
                const dist = Math.hypot(hit.x - pos[0], hit.y - pos[1])
                const { dist: startDist, scale: startScale } = scaleGrab.current
                setStickerScale(
                  THREE.MathUtils.clamp(
                    startScale * (dist / startDist),
                    MIN_SCALE,
                    MAX_SCALE,
                  ),
                )
              }
            }}
            onPointerUp={(e) => {
              ;(e.target as Element).releasePointerCapture(e.pointerId)
              setDrag(null)
            }}
          >
            <meshStandardMaterial
              map={sticker}
              transparent
              roughness={0.1}
              {...headMask}
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/scene.gltf")
